### ISSUE TITLE
Logo for timetable

### ISSUE THREAD

**Issue by zuurw** [jmblount/timetable#1]
Hello, how are you? I would like to know if you need a logo for you project?  Im a Graphic Designer that likes to contribute to open source projects and I would like to work with you in this project.
I remember when I used the timetable when I was a student :)

If you want just tell me what you want and need for the logo?

Cheers!

**Comment by zuurw** [comment]
Hello @jmblount  , Im going to close this issue, if you need my help with the logo you can reopen.
Best Regards.

**Comment by jmblount** [comment]
Hi- I'm apologize for not replying in time - I just noticed you brought this up  when I got the email telling me it was closed :/ - It is to my surprise that anyone has payed attention to this honestly :) - I would love it if you could - though it may need some requirements - it'll need have enough resolution or simplicity to look decent in a small area (eg: 64x64 for icons).
Thank you though - you have brought me back to this project - and I'll have to start cleaning up the mess that is the project now :) 
Again, thank you, and hope to hear soon

**Comment by zuurw** [comment]
Hi @jmblount, no problem!
The logo it wil have enough resolution, thats not a problem.

Do you have something in your mind? any ideas for the logo? colors?
Can you give me or tell somehing for my inspirations?

The timetable is something like I used in paper when I was young in the school?

Greetings!

**Comment by jmblount** [comment]
Heh, I'm never usually this creative about these kind of things but here goes- 
I think some ideas could be the idea of using the generic 'student'- like a graduation hat - and then implement it in with design, As long as the colors compliment each other, it is perfectly fine to run free - preferably stick with any primary color for the main color, or even B&W!

Really, the whole use of it is a replacement of the timetable that like you said was something you used on paper when you were in school- but with how students are getting more tech and even getting given laptops in school- its more practical for digtalising how you interact with going about school - so you could even run round with the idea of a technology device and a paper timetable grid laying over the screen maybe? Again I'm certainly not the most creative kind of person so you can really run wild with ideas, as long as it's relevant to the purpose of the application :)

Hello to you too :)

**Comment by zuurw** [comment]
The idea of the graduation hat it´s really good :) 
Now I have something to start, I will post something here soon.

Greetings!

**Comment by zuurw** [comment]
Hi @jmblount, here is my design for timetable, for the concept I create a graduation student hat with straight lines and for the timetable I create a hexagon with little squares that represent the lessons times.

For the colors I used gray with variations with blue and pink, I think they look really good.

You can see also that I create to diferent sizes of the hexagon, you choose what it fits best with the project.

I create also 2 app buttons, I dont know if you are going to create a app in the future.

See if you like the logo and if you want to change or a new design, just say it.

I will wait for your feedback.

Greetings!


![proposal](https://user-images.githubusercontent.com/40801473/42561749-d0749894-84f1-11e8-9227-9ab2bb3c4f66.png)

**Comment by jmblount** [comment]
Hi-

I really like your logo ideas! You wouldn't mind getting just the blue & pink one with the larger hexagon style? I'm going to try changing the favicon.ico file with it :) @zuurw

**Comment by zuurw** [comment]
I used the font Futura, I think it looks good with the logo.


![proposal typeface](https://user-images.githubusercontent.com/40801473/42586753-ba65c9e4-8530-11e8-863b-5cd233d5b562.png)

**Comment by zuurw** [comment]
Hello I create the PR with the files.
Do you need something more from me?
Do you have other projects that I can work?
Cheers!

**Comment by jmblount** [comment]
Hey! Thank you for making the PR, I'll attempt to close this now - but right now I don't have anything to work sadly unless you want to contribute to the python, though any issues ill leave for the PR :)
Thank you!
